package raf.pp;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 11 11:46:19 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 33;
  public static final int CONST = 16;
  public static final int CHAR = 5;
  public static final int EQUALS = 31;
  public static final int INT = 3;
  public static final int FOR = 12;
  public static final int MINUS = 18;
  public static final int WRITE = 8;
  public static final int AND = 35;
  public static final int SEMICOLON = 23;
  public static final int LT = 28;
  public static final int LP = 20;
  public static final int OR = 34;
  public static final int BOOL = 6;
  public static final int COMMA = 24;
  public static final int DOTDOT = 37;
  public static final int DIV = 36;
  public static final int RP = 21;
  public static final int PLUS = 17;
  public static final int ASSIGN = 22;
  public static final int MAIN = 2;
  public static final int IF = 9;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int LCB = 25;
  public static final int REAL = 4;
  public static final int READ = 7;
  public static final int WHILE = 11;
  public static final int THEN = 10;
  public static final int MTO = 29;
  public static final int DIFF = 32;
  public static final int STRUCT = 14;
  public static final int RCB = 26;
  public static final int LTO = 30;
  public static final int DO = 13;
  public static final int MT = 27;
}

